# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Append node_params list into NodeName list
  ansible.builtin.set_fact:
    slurm_conf_dict: >-
      {{
        slurm_conf_dict
        | combine(
            {
              'NodeName': (slurm_conf_dict.NodeName | default([])) + node_params
            },
            recursive=True
          )
      }}
  when: node_params is defined and node_params

- name: Append Partition
  ansible.builtin.set_fact:
    slurm_conf_dict: >-
      {{
        slurm_conf_dict
        | combine(
            {
              'PartitionName': (slurm_conf_dict.PartitionName | default([])) + [partition_params]
            },
            recursive=True
          )
      }}
  when: node_params is defined and node_params

- name: Add gpu parameters to slurm conf
  ansible.builtin.set_fact:
    slurm_conf_dict: "{{ slurm_conf_dict | combine(gpu_slurm_conf) }}"
  when: gpu_params is defined and gpu_params

- name: Add dbd parameters to slurm conf
  ansible.builtin.set_fact:
    slurm_conf_dict: "{{ slurm_conf_dict | combine(dbd_slurm_conf) }}"
  when: dbd_list is defined and dbd_list
