# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Check if remote host is reachable via SSH
  ansible.builtin.wait_for:
    host: "{{ item }}"
    port: 22 # TODO: make it configurable
    timeout: 10
    state: started
  delegate_to: localhost
  register: ssh_check
  ignore_errors: true
  ignore_unreachable: true

- name: Block when ssh_check is success
  when: ssh_check is success
  block:
    - name: Initialize ctld_state dict
      ansible.builtin.set_fact:
        ctld_state: "{{ ctld_state | default({}) | combine({item: false}) }}"

    - name: Check if slurmctld is running on remote host
      ansible.builtin.service_facts:
      delegate_to: "{{ item }}"
      register: service_facts

    - name: Update ctld_state if slurmctld is running
      ansible.builtin.set_fact:
        ctld_state: "{{ ctld_state | combine({item: true}) }}"
      when:
        - service_facts is success
        - ansible_facts.services['slurmctld.service'] is defined
        - ansible_facts.services['slurmctld.service'].state == 'running'

    - name: Update /etc/hosts with controller hostname and IP
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^{{ ip.value }}\s+{{ ip.key }}'
        line: "{{ ip.value }} {{ ip.key }}"
        state: present
      loop: "{{ ip_name_map | dict2items }}"
      loop_control:
        loop_var: ip
      delegate_to: "{{ item }}"

    - name: Trigger the scontrol reconfigure
      ansible.builtin.command: scontrol reconfigure
      changed_when: scontrol_reconfig.rc == 0
      failed_when: false
      register: scontrol_reconfig
      delegate_to: "{{ item }}"
      when:
        - ctld_state[item] is true
