# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Slurm dict ops
  ansible.builtin.set_fact:
    apply_config: "{{ __default_config }}"

- name: Read NodeName parameters
  ansible.builtin.include_tasks: read_node_idrac.yml
  when: cmpt_list
  loop: "{{ cmpt_list }}"

- name: Slurm dict ops
  ansible.builtin.set_fact:
    slurm_conf_dict: "{{ apply_config['slurm'] }}"
    slurmdbd_conf_dict: "{{ apply_config['slurmdbd'] }}"

- name: Build slurm.conf
  ansible.builtin.include_tasks: build_slurm_conf.yml

- name: Slurm dbd opts
  ansible.builtin.set_fact:
    slurmdbd_conf_dict: "{{ slurmdbd_conf_dict | combine({'DbdHost': ctld_list[0], 'StorageHost': ctld_list[0]}) }}"
  when: ctld_list

- name: Check .conf files existence
  ansible.builtin.stat:
    path: "{{ slurm_config_path }}/{{ item.0 }}/etc/slurm/{{ item.1 }}.conf"
  when: ctld_list
  loop: "{{ ctld_list | product(conf_files | default([])) }}"
  register: ctld_conf_files

# - name: Prepare list for conf merge
#   ansible.builtin.set_fact:
#     conf_merge_list: "{{ ctld_list | product(configs_input.keys() | default([])) }}"

# TODO: Move to input validation with all confs


# - name: Create all .conf for ctld only Write all files default config
#   ansible.builtin.template:
#     src: "{{ item.1 }}.conf.j2"
#     dest: "{{ slurm_config_path }}/{{ item.0 }}/etc/slurm/{{ item.1 }}.conf"
#     owner: "{{ root_user }}"
#     group: "{{ root_group }}"
#     mode: "{{ conf_file_mode }}"
#   when: ctld_list
#   loop: "{{ ctld_list | product(conf_files | default([])) }}"
#   register: ctld_conf_files

- name: Conf merge and write using slurm_conf module
  ansible.builtin.include_tasks: conf_merge.yml
  when: ctld_list
  loop: "{{ ctld_list | product(configs_input.keys() | default([])) }}"
  # debugger: always
# TODO: To apply the cluster_name after merge

- name: Check if cluster running
  ansible.builtin.include_tasks: check_ctld_running.yml
  when:
    - ctld_list
    - ctld_conf_files is changed
  loop: "{{ ctld_list }}"
